version: '3.4'

services:
    heimdall:
        image: linuxserver/heimdall:latest
        volumes:
            - /home/dave/appdata/heimdall:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        ports:
            - 1080:80
            - 1443:443
        restart: unless-stopped   

    tautulli:
        image: tautulli/tautulli:latest
        volumes:
            - /home/dave/docker/appdata/tautulli:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        ports:
            - 8181:8181
        restart: unless-stopped    

    overseerr:
        image: linuxserver/overseerr:latest
        volumes:
            - /home/dave/appdata/overseerr:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        ports:
            - 5055:5055
        restart: unless-stopped    

    embystat:
       image: lscr.io/linuxserver/embystat
       container_name: embystat
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=America/New_York
       volumes:
         - /home/dave/appdata/embystat:/config
       ports:
         - 6555:6555
       restart: unless-stopped
